# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

inhibit_all_warnings!

def common_pods
    
    pod 'QMUIKit'
    
end

def xh_pods
    
end

target 'boxue-oc' do
    common_pods
end
